export const partnersData = [
    { id: 1, name: 'SMAR' },
    { id: 2, name: 'BATI SERVICES' },
    { id: 3, name: 'METCH ELEC' },
    { id: 4, name: 'BTA' },
    { id: 5, name: 'GLOBAL TRANS' },
    { id: 6, name: 'LES ACIERIES DU CAMEROUN' },
    { id: 7, name: 'FOKOU LOGISTIC' },
    { id: 8, name: 'BOCOM' },
    { id: 9, name: 'BOCOM PETROLEUM' },
    { id: 10, name: 'ERNO' },
    { id: 11, name: 'ESER CONTRACTING' },
    { id: 12, name: 'CAMEROUN TIMBER' },
    { id: 13, name: 'SEFAC' },
    { id: 14, name: 'NAMBOIS' },
    { id: 15, name: 'AFRIMAR' },
    { id: 16, name: 'STBC' },
    { id: 17, name: 'NEGRI CAMEROUN' },
    { id: 18, name: 'TRANSAFRIQUE' },
    { id: 19, name: 'CETP' },
    { id: 20, name: 'HYSACAM' },
];
